"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6jp=&ahd(x0f&gg8w$sk7b)v3+w+9cn)$ll^c63pds0hc4_)$='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    'shop_flower',
    "cloudinary",
    "cloudinary_storage",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

CSRF_TRUSTED_ORIGINS = [
    "https://tiemhoacozy.com",
    "https://www.tiemhoacozy.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
import os

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_URL = "http://127.0.0.1:8000"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'tiemhoacozy@gmail.com'
EMAIL_HOST_PASSWORD = 'sams vzve dzhe htbq'

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="dmvsdbvjj",
    api_key="925496818226517",
    api_secret="WyjYs9FMK-ujz6fk1sbtdw7aKR4",
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# tài khoản shop (thay bằng thông tin thật)
SHOP_BANK_ACCOUNT = "0936033374"
SHOP_BANK_NAME = "MBBank"          # tên hiển thị
SHOP_BANK_BENEFICIARY = "PHAM XUAN VINH" # tên chủ tài khoản
SHOP_BANK_GUI = "A000000727"            # giữ mặc định cho POC (NAPAS-like)
SHOP_BANK_SUB = None
SHOP_BANK_CITY = "HANOI"
SHOP_BANK_BIN = "970422"

# ===== VietQR =====
VIETQR_CLIENT_ID = "e5b3e906-251a-45ed-9831-064dba387b96"
VIETQR_API_KEY = "679f07bb-1317-4cb8-80f8-1d0b93bb55cb"

VIETQR_BANK_BIN = "970422"
VIETQR_ACCOUNT_NO = "0936033374"
VIETQR_ACCOUNT_NAME = "PHAM XUAN VINH"