# Generated by Django 5.2.10 on 2026-01-27 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('chờ duyệt', 'Chờ duyệt'), ('đang giao', 'Đang giao'), ('hoàn tất', 'Hoàn tất'), ('hủy', 'Hủy')], default='chờ duyệt', max_length=50),
        ),
    ]
