# Generated by Django 5.2.10 on 2026-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0003_remove_order_order_date_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipper_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=1000),
        ),
    ]
