# Generated by Django 5.2.10 on 2026-01-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0004_order_shipper_number_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
    ]
