# Generated by Django 5.2.10 on 2026-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0005_order_note_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerbatch',
            name='remaining_quantity',
            field=models.IntegerField(editable=False),
        ),
    ]
