# Generated by Django 5.2.10 on 2026-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0006_alter_flowerbatch_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='flower_type',
        ),
        migrations.AddField(
            model_name='flower',
            name='flower_types',
            field=models.ManyToManyField(blank=True, related_name='flowers', to='shop_flower.flowertype'),
        ),
    ]
