# Generated by Django 5.2.10 on 2026-02-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0008_order_created_at_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
