# Generated by Django 5.2.10 on 2026-01-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_flower', '0008_rename_voucher_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='voucher',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_flower.user'),
        ),
        migrations.AlterField(
            model_name='productfunnellog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_flower.user'),
        ),
    ]
